### ISSUE TITLE
Prefer tabs or spaces?

### ISSUE THREAD

**Issue by kalbasit** [dtannen/monitor#3]
The .c and .h files have mixed spaces/tabs, please choose one. I can help you (with a PR) clean that up but which one do you prefer? Personally I prefer 2 spaces.

**Comment by dtannen** [comment]
Thanks for contributing.  2 spaces is fine.

**Comment by kalbasit** [comment]
Of course. #4 re-indents with two spaces. Please note that this conflicts with #2, if you merge #4 first I will re-adjust #2 and get it ready to be merged.

Thanks

**Comment by dtannen** [comment]
done.
